name: Android CI Debug Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # --- ДОБАВЛЕНО: Декодируем и сохраняем debug.keystore из секрета ---
    - name: Decode Debug Keystore
      run: echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 --decode > ${{ github.workspace }}/debug.keystore
      # Проверка, что файл создан (опционально)
      # run: ls -l ${{ github.workspace }}/debug.keystore

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # --- ИЗМЕНЕНО: Передаем путь и пароли из секретов в Gradle ---
    - name: Build with Gradle
      env:
        DEBUG_STORE_FILE: ${{ github.workspace }}/debug.keystore
        DEBUG_STORE_PASSWORD: ${{ secrets.DEBUG_STORE_PASSWORD }}
        DEBUG_KEY_ALIAS: ${{ secrets.DEBUG_KEY_ALIAS }}
        DEBUG_KEY_PASSWORD: ${{ secrets.DEBUG_KEY_PASSWORD }}
      run: ./gradlew assembleDebug -PdebugStoreFile=$DEBUG_STORE_FILE -PdebugStorePassword=$DEBUG_STORE_PASSWORD -PdebugKeyAlias=$DEBUG_KEY_ALIAS -PdebugKeyPassword=$DEBUG_KEY_PASSWORD

    # --- Загружаем ТОЛЬКО APK ---
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: moonlight-debug-apk
        path: app/build/outputs/apk/nonRoot/debug/app-nonRoot-debug.apk
        retention-days: 5
