name: Generate Debug Keystore

on:
  workflow_dispatch: # Запуск вручную

jobs:
  generate_key:
    runs-on: ubuntu-latest

    steps:
    # Устанавливаем Java, т.к. keytool входит в JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Генерируем ключ
    - name: Generate Debug Keystore
      run: |
        keytool -genkey -v -keystore ${{ github.workspace }}/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
        echo "Keystore generated."
        ls -l ${{ github.workspace }}/debug.keystore

    # Загружаем ключ как артефакт
    - name: Upload Debug Keystore
      uses: actions/upload-artifact@v4
      with:
        name: debug-keystore-file # Имя артефакта
        path: ${{ github.workspace }}/debug.keystore
        retention-days: 1 # Хранить только 1 день (нам нужно только скачать)
